#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as a subshell, like 'ksh -c
#       ./gradlew' or 'bash -c ./gradlew'.
#
#       POSIX compliance includes, but is not limited to:
#       * All variable expansions done via $var, ${var}, or $((var)).
#       * Use of functions defined via $() and `` not being treated as
#         commands. $() is preferred over ``.
#       * Use of 'case' statement only for pattern matching (pattern can be
#         composed of '|' to match many at once).
#       * Use of '#' for comments (not '#' for preprocessing or in patterns).
#       * The '&&' and '||' operators to short-circuit do not fail for the
#         last command in a pipeline.
#       * The '!' right after 'if' to test for "not".
#       * Use of '${var#word}' and '${var%word}' for removing leading/trailing
#         substrings.
#       * Use of 'IFS= read -r line' (or 'read -r line') to read lines;
#         'while IFS= read -r line; do something; done' is the recommended
#         pattern for reading input line by line.
#       * Use of 'while loop; do something; done', 'until loop; do something; done'.
#
#   To improve performance, the Gradle Wrapper script automatically sets the
#   following environment variables to improve performance on POSIX systems:
#
#   * JAVA_HOME - The location of the Java installation (for Java exec).
#     The script will try to set this based on JAVA_HOME environment variable,
#     or fall back to 'java' command location.
#   * APP_HOME - The location of the Gradle Wrapper script.
#   * APP_BASE_NAME - The name of the Gradle Wrapper script (excluding extension).
#   * DEFAULT_JVM_OPTS - The default JVM options used when not explicitly
#     provided via environment variables or gradle.properties.
#
#   Additionally, Gradle overrides the following environment variables to control
#   its own JVM settings:
#
#   * GRADLE_OPTS
#   * JAVA_OPTS
#
#   The script uses the following variables for internal bookkeeping:
#
#   * GRADLE_EXIT_CONSOLE - When set to 'true', the script will skip the
#     pagination of the build output (for non-interactive builds). It will
#     also disable console logging for the build (except for errors) as
#     defined by the Gradle 'quiet' and 'stacktrace' command line options.
#   * APP_HOME - The location of the Gradle Wrapper script.
#   * APP_BASE_NAME - The name of the Gradle Wrapper script (without file extension).
#   * REPO_ROOT - The root of the Git repository (if running in a Git
#     repository). May be used to run the build from outside of the build
#     directory (i.e., when started from the root of the repository).
#   * GRADLE_USER_HOME - The Gradle user home directory (used to store
#     caches, wrapper caches, etc.).
#
#   In addition, the script uses the following variables for passing
#   parameters to the Gradle user home, which is used for caching:
#
#   * GRADLE_USER_HOME - The Gradle user home directory.
#   * GRADLE_WRAPPER_USER_HOME - If specified, the Gradle user home used
#     for storing the wrapper caches is overridden to this directory.
#   * GRADLE_OPTS - The JVM arguments for Gradle (overrides any JVM args
#     that would be passed to the Gradle command).
#   * JAVA_OPTS - The JVM arguments for the Java runtime (overrides any
#     JVM args that would be passed to the Java command).
#
#   This script also uses the following variables for internal configuration:
#
#   * GRADLE_WRAPPER_PROPERTIES - The properties file that configures the
#     wrapper location. The default is "$APP_HOME/gradle/wrapper/gradle-wrapper.properties".
#   * GRADLE_WRAPPER_JAR - The JAR file that is the wrapper JAR. The default
#     is "$APP_HOME/gradle/wrapper/gradle-wrapper.jar".
#
#   You can find more information at:
#   * https://docs.gradle.org/current/userguide/gradle_wrapper.html
#   * https://gradle.org/help/gradle-wrapper
#
#   The specific entries in the wrapper configuration file 'gradle-wrapper.properties'
#   are used to specify:
#   * The Gradle distribution type (bin or all) via the 'distributionType' entry.
#     The default is 'bin' which only contains the Gradle binaries (no documentation).
#   * The Gradle distribution URL via the 'distributionUrl' entry.
#     The default is a URL from the Gradle website.
#   * The location of the wrapper JAR via the 'jarUrl' entry.
#     The default is a URL from the Gradle website.
#   * The location of the wrapper properties file relative to the location
#     of the wrapper script.
#
#   The wrapper script only supports configuration of the distribution via
#   the 'gradle-wrapper.properties' file. The wrapper script does not support
#   configuration of the JVM or Java arguments besides what is provided via
#   environment variables.
#
#   The following environment variables are supported for customization:
#
#   * GRADLE_OPTS - JVM arguments for Gradle.
#   * JAVA_OPTS - JVM arguments for the Java runtime.
#   * GRADLE_USER_HOME - Directory for Gradle user caches.
#   * GRADLE_WRAPPER_USER_HOME - If set, the Gradle user home directory used
#     for storing the wrapper caches is overridden to this directory.
#
#   The script uses the following exit codes:
#   0  - successful execution
#   1  - general failure
#   2  - incorrect usage (e.g., invalid command line option)
#   3  - build failure (e.g., compilation error)
#   4  - Java not found
#   5  - Wrapper JAR not found (should not happen for a valid Gradle Wrapper)
#   6  - Wrapper properties not found (should not happen for a valid Gradle Wrapper)
#   7  - Wrapper JAR or properties file is corrupt or not readable
#   8  - Invalid Gradle distribution
#   9  - Could not find a suitable Java installation
#   10 - Invalid environment configuration (e.g., HOME variable not set)
#   11 - Could not find javac (Java compiler) in PATH when running in daemon mode
#   12 - Daemon connection error
#   13 - Could not find Java launcher in JAVA_HOME or PATH
#
#   If any of these environment variables are mentioned in the script
#   to change the behavior of the script, the script will try to find
#   the corresponding environment variable and use it to change the
#   behavior as documented.
#
#   The Gradle Wrapper is maintained by the Gradle team and licensed
#   under the Apache License, Version 2.0.
#
#   The script is derived from the Gradle project.
#   https://github.com/gradle/gradle/blob/master/gradlew
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$(cd "${APP_HOME:-./}" && pwd -P) || exit

# Use the maximum available file descriptors if 'ulimit -n -H -C' is supported and we are not in daemon mode.
if command -v ulimit > /dev/null 2>&1; then
    if [ -z "$GRADLE_EXIT_CONSOLE" ]; then
        if [ -n "$(ulimit -n -H -C 2>&1 | grep -v 'invalid')" ]; then
            ulimit -n -H -C -- --hard 2>/dev/null || \
                ulimit -n -H -C 1024 2>/dev/null
        fi
    fi
fi

# Collect all arguments for the java command, following the shell quoting and substitution rules
# Follow the following rules:
#   * Recognize quoted arguments with the same quotes as the shell uses.
#   * Recognize spaces as separators.
#   * Only split on arguments if the shell would split.
#   * Do not split on escaped characters.
#   * Continue to split after '--' equals separator, to preserve '--abc=def' as a single argument.
#   * Split only on ' ', which is the only character that is both non-escape and non-comment (with comments).
#   * Recognize options that typically involve '=' as a single argument,
#     e.g., --project-prop=value is a single argument, even if it contains spaces.
#
#   This script does not split on spaces that occur within '--' arguments or
#   arguments containing '--' (e.g., '-- --arg' will be two arguments: '--' and '--arg').
#   This is consistent with the behavior of the typical 'sh' shell.
#
#   This script does not expand wildcards by default, but if the variable
#   EXPAND_WILDCARDS is set to 'true', it will expand wildcards.
#   This is useful when the wrapper is being used in a build environment that
#   does not support it (e.g., older shells or Windows).
#   See: https://github.com/gradle/gradle/issues/22750
#   The default value is 'false' to align with the behavior of previous Gradle versions.

if [ -z "$GRADLE_EXIT_CONSOLE" ]; then
    GRADLE_EXIT_CONSOLE=false
fi

# The default is to not expand wildcards.
: "${EXPAND_WILDCARDS:=false}"

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java > /dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if [ -n "$GRADLE_EXIT_CONSOLE" ]; then
    # For non-interactive builds, we can use 'ulimit' if available.
    if command -v ulimit > /dev/null 2>&1; then
        if [ -z "$(ulimit -n -H -C 2>&1 | grep -v 'invalid')" ]; then
            # The limit is not of the type 'hard' and is not the 'hard' limit, so it's a 'soft' limit.
            # We cannot set the 'soft' limit to unlimited, so we set it to the 'hard' limit.
            ulimit -n -S -C -- $(ulimit -n -H -C) 2>/dev/null
        fi
    fi
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in single quotes, so that it is not re-expanded.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs > /dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the arguments and quotes unquoted.
#
# In Bash we could simply go:
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# In POSIX sh we cannot use arrays, so we write to a temporary file and use the
# . command to read the arguments.
# The 'eval' is needed to process the arguments as a single command for 'xargs'.
if ! eval "set -- $(
    printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" | \
    xargs -n1 | \
    sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' | \
    tr '\n' ' ' )" 2>/dev/null; then
    die "xargs failed to parse the JVM arguments. This might be a bug in the Gradle Wrapper.
    Please report this to the Gradle project: https://github.com/gradle/gradle/issues"
fi

# Collect all arguments for the 'java' command with the escaped arguments.
eval set -- "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" '"$@"'

# Use 'exec' to replace the current shell with the java command.
exec "$JAVACMD" "$@"
