name = "student-app"
pages_build_output_dir = "./dist"
compatibility_date = "2026-03-07"

[[d1_databases]]
binding = "DB"
database_name = "college_db"
database_id = "382dd54e-c53c-4ca2-b385-9d2edf1a1dce"

