name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.11

      - name: Upload APK
        # Change this line from v2 to v4
        uses: actions/upload-artifact@v4 
        with:
          name: Plotter-APK
          # Path to where Buildozer saves the finished APK
          path: bin/*.apk
          
